#ifndef QTNICOLIVELIB_GLOBAL_H
#define QTNICOLIVELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTNICOLIVELIB_LIBRARY)
#  define QTNICOLIVELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTNICOLIVELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTNICOLIVELIB_GLOBAL_H
